global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "url-shortener-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: "analytics-consumer"
    metrics_path: /metrics
    static_configs:
      - targets: ["analytics-consumer:9091"]
