global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # ===== API service =====
  - job_name: "url-shortener-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8080

  # ===== Analytics consumer =====
  - job_name: "analytics-consumer"
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9091
